propagate mcp=master for SNO to reg_expand.sh

diff --git a/bin/lab-analyzer b/bin/lab-analyzer
--- a/bin/lab-analyzer
+++ b/bin/lab-analyzer
@@ -63,8 +63,8 @@ function f_validate_worker_nodes {
 }
 
 # Let's go 
-if ! ssh $REG_KNI_USER@$REG_OCPHOST pwd  &>/dev/null ; then
-	echo "Error: Please check ssh info in lab.config" >&2
+if ! ssh $REG_KNI_USER@$REG_OCPHOST oc get node  &>/dev/null ; then
+	echo "Error: Please confirm REG_KNI_USER and REG_OCPHOST in lab.config" >&2
 	exit 1
 fi
 
