change lab-analyzer to ssh core@ip

diff --git a/bin/lab-analyzer b/bin/lab-analyzer
--- a/bin/lab-analyzer
+++ b/bin/lab-analyzer
@@ -38,28 +38,43 @@ function exit_error() {
     exit 1
 }
 
+is_ip() {
+    local ip_regex='^([0-9]{1,3}\.){3}[0-9]{1,3}$'
+    [[ $1 =~ $ip_regex ]]
+}
+#if is_ip "$1"; then
+#    echo "It's an IP address."
+#else
+#   echo "It's a hostname."
+#fi
 
 function do_ssh() {
-    ssh_opts="-o StrictHostKeyChecking=no -o PasswordAuthentication=no"
-    local user_host user host ssh_cmd
-    user_host=$1; shift
-    user=`echo $user_host | awk -F@ '{print $1}'`
-    host=`echo $user_host | awk -F@ '{print $2}'`
-    ssh_cmd=""
-    if [ -z "$user" ]; then
-        exit_error "do_ssh: user was blank: $user_host"
-    fi
-    if [ -z "$host" ]; then
-        exit_error "do_ssh: host was blank: $user_host"
-    fi
-    ssh_cmd="ssh $ssh_opts $user_host bash -c \"$@\""
+    local user_host="$1"
+    shift
+    local ssh_opts="-o StrictHostKeyChecking=no -o PasswordAuthentication=no"
+    local user host ssh_cmd
 
-    echo CMD: $ssh_cmd  >&2
-    $ssh_cmd
+    # Parse user and host from user_host
+    user=$(echo "$user_host" | awk -F@ '{print $1}')
+    host=$(echo "$user_host" | awk -F@ '{print $2}')
+
+    # Check if user and host are valid
+    if [ -z "$user" ] || [ -z "$host" ]; then
+        echo "Error: Invalid user/host: $user_host" >&2
+        return 1
+    fi
+
+    # Create the ssh command with the given commands
+    ssh_cmd="ssh $ssh_opts $user_host \"bash -c '$@'\""
+
+    # Echo the command for debugging
+    echo "CMD: $ssh_cmd" >&2
+
+    # Execute the command
+    eval $ssh_cmd
     local rc=$?
     return $rc
 }
-
 
 function f_verify_lab_config {
 echo IN: f_verify_lab_config  >&2
@@ -72,7 +87,7 @@ echo IN: f_verify_lab_config  >&2
     local DEST="$REG_KNI_USER@$REG_OCPHOST"
     #workers=$(ssh $DEST "oc get nodes --selector='node-role.kubernetes.io/worker' -o jsonpath='{.items[*].metadata.name}'")
     workers=$(do_ssh $DEST "source $reg_dir/lab.config &&  oc get nodes --request-timeout=30s --selector='node-role.kubernetes.io/worker' -o jsonpath='{.items[*].metadata.name}'")
-    
+
     if [ $? -ne 0 ] ; then
         echo "Cannot ssh to bastion $DEST" >&2
         exit 1
@@ -94,8 +109,10 @@ echo IN: f_verify_lab_config  >&2
     fi
 
     # Check lab.config consistency
-    #rem_exports=$(ssh $DEST "cd $reg_dir && cat lab.config | grep export | grep -v '#' ")
-    rem_exports=$(do_ssh $DEST "cd $reg_dir && cat lab.config | grep export | grep -v '#' ")
+    # ssh + grep has too much syntax headaches. scp and then grep local is easier.
+    scp $DEST:$reg_dir/lab.config /tmp/lab.config
+    rem_exports=$(grep export /tmp/lab.config | grep -v '#')
+
     local_exports=$(cd $REG_ROOT && cat lab.config | grep export | grep -v '#')
     if [ "$rem_exports" != "$local_exports" ]; then
         if [ "$auto_fix" == "true" ]; then
@@ -107,8 +124,7 @@ echo IN: f_verify_lab_config  >&2
         fi
     fi
 
-    # A super convolute mess. We need to make init-lab (to initialize CLUSTER_TYPE) on the bastion 
-    # first before we can run make init for SRIOV/UNIV/
+    # The bastion also needs lab-init (for CLUSTER_TYPE) before we can init SRIOV/UNIV/
     if [ "$auto_fix" == "true" ]; then
         echo "CMD: ssh $DEST cd $reg_dir && source bootstrap.sh && make init-lab" >&2
         #ssh $DEST "cd $reg_dir && source bootstrap.sh && make init-lab"
@@ -121,7 +137,8 @@ echo IN: f_verify_lab_config  >&2
         if [ "$auto_fix" == "true" ]; then
             echo "WARN: SRIOV-config/UNIV is not yet initialized on the bastion" >&2
             echo "auto_fix is ON. Fixing it"  >&2
-            (do_ssh $DEST "cd $reg_dir && source bootstrap.sh && cd SRIOV-config/UNIV && make init")
+            #(do_ssh $DEST "cd $reg_dir && source bootstrap.sh && cd SRIOV-config/UNIV && make init")
+            do_ssh $DEST "cd $reg_dir && source bootstrap.sh && cd SRIOV-config/UNIV && make init"
         else
             echo "ERROR: SRIOV-config/UNIV is not yet initialized on the bastion" >&2
             echo "Hint: go to $reg_dir/SRIOV-config/UNIV on the bastion and 'make init'" >&2
@@ -195,9 +212,11 @@ function f_validate_worker_nodes {
 
 function create_mirror_repo_on_bastion {
     local_repo_path=$(git rev-parse --show-toplevel)
-    remote_user="$REG_KNI_USER"
-    remote_host="$REG_OCPHOST"
-    #
+    remote_user=$1
+    remote_host=$2
+
+    echo "HN create_mirror_repo_on_bastion on $2 " >&2
+
     local_basename=$(basename "$REG_ROOT")
 
     # Get the current branch name from the local repository
@@ -246,33 +265,52 @@ function create_mirror_repo_on_bastion {
 }
 
 # continue
-if [ "$(hostname)" != "$REG_OCPHOST" ]  &&  [ "$(hostname -i)" != "$REG_OCPHOST" ] ; then
-    echo "$0 is running on the controller ... check lab.config match" >&2
+if [ "$(hostname)" != "$REG_OCPHOST" ] ; then
+    echo "$0 is NOT on the bastion ... mirror check lab.config match" >&2
     # mirror repo in a sub-shell, to avoid all the unwanted messages
     (
         # Install regulus repo on the bastion if applicable
-        create_mirror_repo_on_bastion
+        create_mirror_repo_on_bastion "${REG_KNI_USER}" "${REG_OCPHOST}"
+
     ) > lab-init.log 2>&1
     f_verify_lab_config 
 else
     echo "$0 is running on the bastion ... skip lab.config match check" >&2
 fi
 
-echo CMD: reg_dir=$reg_dir  >&2
-echo CMD: do_ssh $REG_KNI_USER@$REG_OCPHOST "source $reg_dir/lab.config && oc get node"  >&2
+is_bastion() {
+    [ "$1" == "$REG_OCPHOST" ]
+}
 
-if ! do_ssh $REG_KNI_USER@$REG_OCPHOST "source $reg_dir/lab.config && oc get node"  &>/dev/null ; then
+read -a BM_HOST_ARR <<< "$BM_HOSTS"
+
+for host in "${BM_HOST_ARR[@]}"; do
+    if [ "$(hostname)" != "$host" ] ; then
+        if is_bastion "$host"; then
+            echo "remotehost $host is bastion. Skipping cloning..." >&2
+            continue
+        fi
+        echo "remotehost $host is not bastion. Cloning repo to remotehost" >&2
+        # Mirror repo in a sub-shell to avoid unwanted messages
+        (
+            create_mirror_repo_on_bastion "root" "${host}"
+        ) > rem-init.log 2>&1
+    fi
+done
+
+# check ssh and $reg_dir correctness
+if ! do_ssh "$REG_KNI_USER@$REG_OCPHOST" "cd $reg_dir" ; then
 	echo "Error: Please confirm REG_KNI_USER and REG_OCPHOST in lab.config" >&2
 	exit 1
 fi
 
-
 tb_cluster_type=$(f_get_cluster_type)
 echo "cluster_type=$tb_cluster_type" >&2
 f_validate_worker_nodes
-first_worker="$(echo $worker_names | awk '{print $1}')"
+#first_worker="$(echo $worker_names | awk '{print $1}')"
+first_worker=$OCP_WORKER_0
+first_worker_ip="$(do_ssh $REG_KNI_USER@$REG_OCPHOST "source $reg_dir/lab.config && kubectl get node/\$OCP_WORKER_0 -o=custom-columns=IP:.status.addresses[0].address --no-headers")"
 tb_alloc_cpus="$(do_ssh $REG_KNI_USER@$REG_OCPHOST "source $reg_dir/lab.config && kubectl get node/$first_worker -ojsonpath='{.status.allocatable.cpu}'")"
-
 
 # Round-down to whole CPU if we see like 31500m
 if [[ "$tb_alloc_cpus" == *m ]]; then
@@ -283,18 +321,22 @@ tb_useable_cpus=$(($tb_alloc_cpus-$RESERVED_CPUS))
 echo "useable_cpus=$tb_useable_cpus" >&2
 
 # get worker cpu topology
-cps_string="$(do_ssh $REG_KNI_USER@$REG_OCPHOST "ssh core@$first_worker lscpu" | grep Core)"
+cps_string="$(do_ssh $REG_KNI_USER@$REG_OCPHOST "ssh  -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null core@$first_worker_ip lscpu" | grep Core)"
 if [ -z "$cps_string" ]; then
-    echo "Failed to ssh core@$first_worker. Please setup 'core' login" >&2
+    echo "Failed to ssh core@$first_worker_ip. Please setup 'core' login" >&2
     exit 
 fi
 # extract the number from like "Core(s) per socket:  28"
 tb_cps=$(echo "$cps_string" | awk '{print $NF}')
 echo "core-per-socket=$tb_cps" >&2 
 
-
 f_update_tb_info
 
-echo "$0 completed" >&2
+if [ "$(hostname)" == "$REG_OCPHOST" ] ; then
+    iam="bastion"
+else
+    iam="local"
+fi
+echo "$0 on $iam completed" >&2
 
 # done
