change lab-analyzer to ssh core@ip

diff --git a/bin/lab-analyzer b/bin/lab-analyzer
--- a/bin/lab-analyzer
+++ b/bin/lab-analyzer
@@ -87,7 +87,7 @@ echo IN: f_verify_lab_config  >&2
     local DEST="$REG_KNI_USER@$REG_OCPHOST"
     #workers=$(ssh $DEST "oc get nodes --selector='node-role.kubernetes.io/worker' -o jsonpath='{.items[*].metadata.name}'")
     workers=$(do_ssh $DEST "source $reg_dir/lab.config &&  oc get nodes --request-timeout=30s --selector='node-role.kubernetes.io/worker' -o jsonpath='{.items[*].metadata.name}'")
-    
+
     if [ $? -ne 0 ] ; then
         echo "Cannot ssh to bastion $DEST" >&2
         exit 1
@@ -299,7 +299,7 @@ for host in "${BM_HOST_ARR[@]}"; do
 done
 
 # check ssh and $reg_dir correctness
-if ! do_ssh "$REG_KNI_USER@$REG_OCPHOST" "cd $reg_dir && oc get node &>/dev/null" ; then
+if ! do_ssh "$REG_KNI_USER@$REG_OCPHOST" "cd $reg_dir" ; then
 	echo "Error: Please confirm REG_KNI_USER and REG_OCPHOST in lab.config" >&2
 	exit 1
 fi
@@ -307,7 +307,9 @@ fi
 tb_cluster_type=$(f_get_cluster_type)
 echo "cluster_type=$tb_cluster_type" >&2
 f_validate_worker_nodes
-first_worker="$(echo $worker_names | awk '{print $1}')"
+#first_worker="$(echo $worker_names | awk '{print $1}')"
+first_worker=$OCP_WORKER_0
+first_worker_ip="$(do_ssh $REG_KNI_USER@$REG_OCPHOST "source $reg_dir/lab.config && kubectl get node/\$OCP_WORKER_0 -o=custom-columns=IP:.status.addresses[0].address --no-headers")"
 tb_alloc_cpus="$(do_ssh $REG_KNI_USER@$REG_OCPHOST "source $reg_dir/lab.config && kubectl get node/$first_worker -ojsonpath='{.status.allocatable.cpu}'")"
 
 # Round-down to whole CPU if we see like 31500m
@@ -319,9 +321,9 @@ tb_useable_cpus=$(($tb_alloc_cpus-$RESERVED_CPUS))
 echo "useable_cpus=$tb_useable_cpus" >&2
 
 # get worker cpu topology
-cps_string="$(do_ssh $REG_KNI_USER@$REG_OCPHOST "ssh core@$first_worker lscpu" | grep Core)"
+cps_string="$(do_ssh $REG_KNI_USER@$REG_OCPHOST "ssh  -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null core@$first_worker_ip lscpu" | grep Core)"
 if [ -z "$cps_string" ]; then
-    echo "Failed to ssh core@$first_worker. Please setup 'core' login" >&2
+    echo "Failed to ssh core@$first_worker_ip. Please setup 'core' login" >&2
     exit 
 fi
 # extract the number from like "Core(s) per socket:  28"
