harden PAO and SRIOV config util

diff --git a/SRIOV-config/common/make-common b/SRIOV-config/common/make-common
--- a/SRIOV-config/common/make-common
+++ b/SRIOV-config/common/make-common
@@ -8,19 +8,19 @@ ifndef REG_ROOT
 $(error REG_ROOT is not set. Please 'source ./bootstrap.sh')
 endif
 include ${REG_ROOT}/jobs.config
+include ${REG_ROOT}/lab.config
 
 confirm_bastion: 
-    source ${REG_ROOT}/lab.config && export REG_OCPHOST=$${REG_OCPHOST} 
-    @if [ $$(hostname) != "$${REG_OCPHOST}" ]; then \
-         . ${REG_ROOT}/lab.config && echo "ABorting. Please run this command on the bastion, $${REG_OCPHOST}."; \
-        exit 1; \
-    fi
+	@if [ "$$(hostname)" != "$(REG_OCPHOST)" ]; then \
+		@echo "Aborting. Please run this command on the bastion, $${REG_OCPHOST}."; \
+		exit 1; \
+	fi
 
-init: confirm_bastion:
-	. ${REG_ROOT}/lab.config && ./expand.sh
+init: confirm_bastion
+	@bash ./expand.sh
 
-install: confirm_bastion:
-	. ${REG_ROOT}/lab.config && bash install.sh
+install: confirm_bastion
+	@bash ./install.sh
 
-cleanup: confirm_bastion:
-	. ${REG_ROOT}/lab.config && bash cleanup.sh
+cleanup: confirm_bastion
+	@source ${REG_ROOT}/lab.config && source ${REG_ROOT}/SRIOV-config/config.env && bash ./cleanup.sh
