invoke TRAFFICGEN init during install

diff --git a/templates/trafficgen/run.sh.template b/templates/trafficgen/run.sh.template
--- a/templates/trafficgen/run.sh.template
+++ b/templates/trafficgen/run.sh.template
@@ -9,6 +9,7 @@ source ${REG_ROOT}/templates/common/worker_labels.config
 source ${REG_ROOT}/init.sh
 source ${REG_ROOT}/templates/common/remotehost_functions
 source ${REG_ROOT}/templates/common/functions
+source ${REG_ROOT}/SETUP_GROUP/DPDK/INSTALL/trafficgen.sh 
 
 # Variables if one or more remotehost
 # endpoints are used (topo=ingress)
@@ -36,25 +37,16 @@ max_failures=1          # After this many failed samples=$NUM_SAMPLE the run wil
 tags="dpdk:trafficgen"
 
 # get the PCI address of the TREX interfaces
-device_info=$REG_ROOT/SETUP_GROUP/DPDK/INSTALL/trex-device-info.json  # was created by ../DPDK/INSTALL/"make init" at init-lab time
-query_pci_by_interface() {
-    local json_file=$1
-    local interface_name=$2
-
-    [[ -z "$json_file" || -z "$interface_name" ]] && { echo "Usage: query_pci_by_interface <json_file> <interface_name>"; return 1; }
-
-    local pci_addr
-    pci_addr=$(jq -r --arg iface "$interface_name" '.[] | select(.interface_name == $iface) | .pci_addr' "$json_file")
-
-    if [[ -n "$pci_addr" && "$pci_addr" != "null" ]]; then
-        echo "$pci_addr"
-    else
-        echo "Error: Interface $interface_name not found in $json_file" >&2
-        return 1
-    fi
-}
-pci1=("$(query_pci_by_interface "${device_info}" "$REG_DPDK_NIC_1")")
-pci2=("$(query_pci_by_interface "${device_info}" "$REG_DPDK_NIC_2")")
+pci1=("$(query_pci_by_interface "$REG_DPDK_NIC_1")")
+if [ $? -ne 0 ]; then
+    echo "query_pci_by_interface failed. Did you run SETUP_GROUP/DPDK/INSTALL ?"
+    exit 1
+fi
+pci2=("$(query_pci_by_interface "$REG_DPDK_NIC_2")")
+if [ $? -ne 0 ]; then
+    echo "query_pci_by_interface failed. Did you run SETUP_GROUP/DPDK/INSTALL ?"
+    exit 1
+fi
 TREX_ACTIVE_DEVICES_PCI="$pci1,$pci2"
 TREX_DEVICES_PCI=$TREX_ACTIVE_DEVICES_PCI
 case "${REG_DPDK_NIC_MODEL}" in
